/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cxpqwvtj' at '16/02/06 18:06' with Gradle 2.8
 *
 * @author cxpqwvtj, @date 16/02/06 18:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
