import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'cxpqwvtj' at '16/02/06 18:06' with Gradle 2.8
 *
 * @author cxpqwvtj, @date 16/02/06 18:06
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
    }
}
